#pragma once

#include "InputClientInserer.h"
#include "InputPersonnelInserer.h"
#include "InputCommandeInserer.h"
#include "InputStockInserer.h"
#include "InputPersonnelSupprimer.h"
#include "InputCommandeSupprimer.h"
#include "InputStockSupprimer.h"
#include "InputClientUpdate.h"
#include "InputAdresseClient.h"
#include "InputArticleInserer.h"
#include "InputClientUpdate.h"
#include "InputArticleUpdate.h"
#include "InputPersonnelUpdate.h"
#include "Auth.h"